- name: Install required software
  hosts: testservers

  tasks:
    - yum:
        name: "{{ packages }}"
        state: present
      vars: 
        packages:
         - httpd
      become: true
        
    - service:
        name: httpd
        state: started
        enabled: yes


