---
- hosts: testservers 
  become: True
  tasks:
    - name: Install Apache
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
