- name: Install required software
  hosts: testservers
  become: True
  tasks:
    - yum:
        name: "{{ packages }}"
        state: present
      vars: 
        packages:
         - httpd        
    - service:
        name: httpd
        state: started
        enabled: yes


