- hosts: testservers
  tasks:
    - name: install Apache
      yum: 
        name: httpd 
        state: present
        become: true
        notify:
        - start apache2
  handlers:
    - name: startapache2
      service: 
        name: httpd
        state: started
        enabled: True
